# Generated by Django 5.0.4 on 2024-04-19 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.user')),
            ],
            options={
                'db_table': 'donation',
                'ordering': ['-created_at'],
            },
        ),
    ]
