# Generated by Django 5.0.4 on 2024-04-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='PERSONAL', max_length=20),
        ),
    ]
