# Generated by Django 5.0.4 on 2024-04-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='image_base64',
            field=models.TextField(null=True),
        ),
    ]
