# Generated by Django 5.0.4 on 2024-04-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donation_description_donation_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.user')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
            ],
            options={
                'db_table': 'donation_claim',
                'ordering': ['-claimed_on'],
            },
        ),
    ]
