# Generated by Django 5.0.4 on 2024-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
